import './global.css';

export const metadata = {
  title: 'Welcome to laugh-it-up',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/html5-reset/assets/css/reset.min.css" /> */}
      <body>
        {children}
      </body>
    </html>
  );
}
